"""remove day daily summary column and add day title

Revision ID: a55a2511c7a0
Revises: e798423e3519
Create Date: 2026-03-13 23:50:09.741207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a55a2511c7a0"
down_revision: Union[str, Sequence[str], None] = "e798423e3519"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("days", sa.Column("title", sa.String(), nullable=True))
    op.drop_column("days", "daily_summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "days",
        sa.Column("daily_summary", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.drop_column("days", "title")
    # ### end Alembic commands ###
